name: Rank Lichess Bots

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC

# Add permissions to allow writing to the repository
permissions:
  contents: write  # Grants write access to repository contents

jobs:
  rank-bots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to avoid issues with git push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run rank_bots.py
        run: python rank_bots.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.csv
          git commit -m "Update Lichess bots ranking CSV files" --allow-empty
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
