name: Rank Lichess Bots

# Triggers: Run on push to main branch or daily at 00:00 UTC
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC

jobs:
  rank-bots:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      # Step 4: Run the Python script
      - name: Run rank_bots.py
        run: python rank_bots.py

      # Step 5: Commit and push CSV files to repository
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add *.csv
          git commit -m "Update Lichess bots ranking CSV files" --allow-empty
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
